### ISSUE TITLE
django 1.8.11 is still supported ?

### ISSUE THREAD

**Issue by ghost** [nnseva/django-authenticated-signals#1]
Recently,  an operate log system is developped with django 1.8.11,  this repo seems tobe helpful，but i got an error:   "ImportError: cannot import name MiddlewareMixin" at "authenticated_signals/middleware.py"。

**Comment by ghost** [comment]
comment this line and change "MiddlewareMixin" to "object" will fix

**Comment by nnseva** [comment]
No @hsdtsyl , the django 1.8 and lower doesn't use a common mixin for the middleware. I don't plan to support django lower version.
